layout_spectrum: 0.04802298
typography_spectrum: 0.0794504
color:
  saturation: 0.7795699
  brandStrength: 0.6740074
  lightness: 0.2610514
  rhythmicContrast: 0.5445055
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Behram
